---
engines:
  duplication:
    enabled: true
    exclude_paths:
    - spec/
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- vendor/
