AllCops:
  Exclude:
    - "vendor/**/*"
  TargetRubyVersion: 2.4

Style/BlockComments:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "idcf-your.gemspec"
    - "spec/**/*"
