sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=ed17dad515f8c4f28246a10d13ea6eecd6e5012e6b98a106cbdb300629988c3f
language: ruby
rvm:
  - 1.9.3
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
before_install: gem install bundler
